version: '3.7'

services:
  client:
    container_name: client
    image: euphony_client
    build:
      context: ./
      dockerfile: infra/prod/docker/client/Dockerfile

  nginx:
    container_name: nginx
    image: euphony_nginx
    restart: always
    build:
      context: ./
      dockerfile: infra/prod/docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - service

  service:
    container_name: service
    image: euphony_service
    restart: always
    build:
      context: ./
      dockerfile: infra/prod/docker/service/Dockerfile